<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Version> 8.0.6</Version>
	  <Description>
		  Нугет отвечает за базу данных проекта Casino

		  8.0.6 - Изменена таблица DealerBlackJackSetting. 
		  8.0.5 - Добавлена таблица DealerBlackJackSetting. В таблице GameHistory добавена строка DealerCheating
		  8.0.4 - В перечислении ролей добавлен SuperAdmin.
		  8.0.3 - В таблице Users добавлены поля DataRemove, Role. Добавлены модели карт для Блэкджека.
		  8.0.2 - В базу данных добавлена дата регистрации пользователя и папка с изображениями пользователя.
		  8.0.1-База данных Casino.
	  </Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.18" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.18">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
